### ISSUE TITLE
Add more filter options to filter relevant events/incidents/trials.

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/lessons-learned-framework#2]

**Comment by DirkStolk** [comment]
We also have to filter on lesson characteristics; e.g. provide me with all lessons w.r.t. forest fires, or provide me with all events in The Netherlands. Or should that be done elsewhere?

**Comment by DirkStolk** [comment]
Event type moet geselecteerd worden om verder te kunnen gaan. 
Bovendien moet het geen meerkeuzemogelijkheid zijn; ik wil dat de gebruiker 1 specifiek type kiest.
