### ISSUE TITLE
Protect edit functionality: only owners and editors are allowed to change content.

### ISSUE THREAD

**Issue by erikvullings** [DRIVER-EU/lessons-learned-framework#4]

**Comment by DirkStolk** [comment]
So, we have to determine which types of users we discriminate. Do you have any suggestion?

**Comment by erikvullings** [comment]
There are multiple users:
- Unauthenticated users can view the lessons.
- Users can register themselves via Keycloak (if the Keycloak realm allows it)
- Authenticated users can create new lessons. When creating a new lesson, they automatically become the owner of the lesson.
- Owners of a lesson can assign editors using their email. Authenticated users with this email are allowed to edit (and publish) the lesson too.
- Authenticated users with the role of editor can review and edit all lessons.
- Authenticated users with the role of admin can review and edit all lessons, and also change the access rights (i.e. add or remove document editors).
- These roles are assigned via the Keycloak admin interface.
